from __future__ import annotations

from tools.workflow_cegis.lean_common import (
    lean_list,
    unique_identifiers,
)
from tools.workflow_cegis.model import WorkflowModel

from .errors import ValidationError
from .trace import ObservedAttackTrace


def render_trace_refinement_lean(
    *,
    base_model: WorkflowModel,
    refined_model: WorkflowModel,
    trace: ObservedAttackTrace,
    report: dict,
) -> str:
    namespace = f"{refined_model.namespace_prefix}.TraceRefinement"
    original_ns = base_model.workflow_namespace
    refined_ns = refined_model.workflow_namespace
    evidence_ns = refined_model.evidence_namespace
    event_ids = list(dict.fromkeys(trace.event_ids))
    event_ident = unique_identifiers(event_ids, "event")
    original_action_ident = unique_identifiers(
        [action.id for action in base_model.actions], "action"
    )
    refined_action_ident = unique_identifiers(
        [action.id for action in refined_model.actions], "action"
    )
    field_ident = unique_identifiers(
        [variable.id for variable in refined_model.variables], "field"
    )
    history_ident = unique_identifiers(
        [
            edge["left"]
            for edge in report["separator_analysis"]["honest_attack_edges"]
        ]
        + [
            edge["right"]
            for edge in report["separator_analysis"]["honest_attack_edges"]
        ],
        "history",
    )
    channel_ids = report["separator_analysis"]["separator_basis"]
    channel_ident = unique_identifiers(channel_ids, "channel")
    unknown_events = [
        event for event in event_ids if event not in base_model.action_by_id
    ]
    if not unknown_events:
        raise ValidationError(
            "trace refinement Lean witness requires at least one original alphabet gap"
        )
    gap_event = unknown_events[0]
    final_state = report["refined_replay"]["final_state"]

    lines: list[str] = [
        "import LeanFinance.Epistemic.TraceRefinement",
        f"import {original_ns}",
        f"import {refined_ns}",
        f"import {evidence_ns}",
        "",
        f"namespace {namespace}",
        "",
        "open LeanFinance.Epistemic",
        f"abbrev OriginalAction := {original_ns}.Action",
        f"abbrev RefinedAction := {refined_ns}.Action",
        "",
        "/-- Generated by `python -m tools.trace_refinement refine`. Do not edit by hand. -/",
        "",
        "inductive ObservedEvent where",
    ]
    lines.extend(f"  | {event_ident[event]}" for event in event_ids)
    lines += ["  deriving Repr, DecidableEq", "", "def observedTrace : List ObservedEvent :="]
    lines.append(
        "  " + lean_list([f".{event_ident[event]}" for event in trace.event_ids])
    )
    lines += ["", "def originalResolve : ObservedEvent → Option OriginalAction"]
    for event in event_ids:
        if event in original_action_ident:
            lines.append(
                f"  | .{event_ident[event]} => some .{original_action_ident[event]}"
            )
        else:
            lines.append(f"  | .{event_ident[event]} => none")
    lines += ["", "def refinedResolve : ObservedEvent → Option RefinedAction"]
    for event in event_ids:
        lines.append(
            f"  | .{event_ident[event]} => some .{refined_action_ident[event]}"
        )
    lines += ["", "def refinedTrace : List RefinedAction :="]
    lines.append(
        "  "
        + lean_list(
            [f".{refined_action_ident[event]}" for event in trace.event_ids]
        )
    )
    lines += ["", f"def expectedFinalState : {refined_ns}.State :=", "  {"]
    for variable in refined_model.variables:
        value = "true" if final_state[variable.id] else "false"
        lines.append(f"    {field_ident[variable.id]} := {value}")
    lines += ["  }", ""]
    lines += [
        "def refinementCertificate :",
        "    TraceModelRefinementCertificate",
        "      (Event := ObservedEvent)",
        "      (OriginalAction := OriginalAction)",
        "      (RefinedAction := RefinedAction)",
        f"      {refined_ns}.workflow {refined_ns}.claimState :=",
        "  {",
        "    observedTrace := observedTrace",
        "    originalResolve := originalResolve",
        "    refinedResolve := refinedResolve",
        "    originalGap := by",
        f"      refine ⟨.{event_ident[gap_event]}, ?_, rfl⟩",
        "      simp [observedTrace]",
        "    refinedTrace := refinedTrace",
        "    refinedResolution := by decide",
        "    finalState := expectedFinalState",
        "    replayed := by decide",
        "    violates := by decide",
        "  }",
        "",
        "theorem original_model_has_action_alphabet_gap :",
        "    ∃ event,",
        "      event ∈ refinementCertificate.observedTrace ∧",
        "        refinementCertificate.originalResolve event = none :=",
        "  refinementCertificate.originalAlphabetIncomplete",
        "",
        "theorem refined_model_reproduces_observed_trace :",
        f"    replay {refined_ns}.workflow refinementCertificate.refinedTrace =",
        "      some refinementCertificate.finalState :=",
        "  refinementCertificate.refinedTraceReplays",
        "",
        "theorem observed_attack_violates_refined_claim :",
        f"    {refined_ns}.claimState refinementCertificate.finalState = false :=",
        "  refinementCertificate.refinedTraceViolatesClaim",
        "",
    ]

    greenfield = set(report["separator_analysis"]["greenfield_selection"])
    for channel_id in channel_ids:
        if channel_id not in greenfield:
            continue
        identifier = channel_ident[channel_id]
        theorem_name = f"greenfield_basis_contains_{identifier}"
        lines += [
            f"theorem {theorem_name} :",
            f"    {evidence_ns}.Channel.{identifier} ∈",
            f"      {evidence_ns}.decode {evidence_ns}.selected := by",
            "  decide",
            "",
        ]

    edges = report["separator_analysis"]["honest_attack_edges"]
    if edges and channel_ids:
        edge = edges[0]
        left = history_ident[edge["left"]]
        right = history_ident[edge["right"]]
        separator = channel_ident[channel_ids[0]]
        lines += [
            "def observedAttackSeparatorBasis :",
            f"    List {evidence_ns}.Channel :=",
            f"  [.{separator}]",
            "",
            "theorem refined_separator_basis_distinguishes_observed_attack :",
            f"    SelectedSeparates {evidence_ns}.model",
            f"      observedAttackSeparatorBasis .{left} .{right} := by",
            f"  refine ⟨.{separator}, by simp [observedAttackSeparatorBasis], ?_⟩",
            "  decide",
            "",
        ]

    lines += [f"end {namespace}", ""]
    return "\n".join(lines)
