from __future__ import annotations

from typing import Any

from .canonical import canonical_dumps
from .explore import ExpandedChannel, History
from .model import WorkflowModel
from .lean_common import _history_channel_maps, _render_inductive, lean_list


def _observation_catalog(
    evidence_model: dict[str, Any],
) -> tuple[list[str], dict[str, str]]:
    values: list[str] = []
    histories = [item["id"] for item in evidence_model["histories"]]
    for channel in evidence_model["channels"]:
        for history_id in histories:
            encoded = canonical_dumps(channel["observations"][history_id])
            if encoded not in values:
                values.append(encoded)
    return values, {encoded: f"obs{index}" for index, encoded in enumerate(values)}


def _counterexample_definition(
    *,
    name: str,
    candidate_name: str,
    left: str,
    right: str,
) -> list[str]:
    return [
        f"def {name} :",
        f"    BoundedCounterexample model (decode .{candidate_name}) :=",
        "  {",
        f"    left := .{left}",
        f"    right := .{right}",
        "    leftMember := by simp [model, histories]",
        "    rightMember := by simp [model, histories]",
        "    claimDifferent := by simp [model, claim]",
        "    selectedAgree := by",
        "      intro evidenceChannel member",
        "      cases evidenceChannel <;>",
        "        simp [decode, model, observe] at member ⊢",
        "  }",
        "",
    ]


def render_evidence_lean(
    model: WorkflowModel,
    report: dict[str, Any],
    histories: tuple[History, ...],
    channels: tuple[ExpandedChannel, ...],
) -> str:
    evidence_model = report["evidence_model"]
    synthesis = report["exact_synthesis"]
    history_ident, channel_ident = _history_channel_maps(histories, channels)
    observation_values, observation_ident = _observation_catalog(evidence_model)
    namespace = model.evidence_namespace
    candidate_count = 1 << len(channels)
    selected_mask = synthesis["selected"]["mask"]
    lines: list[str] = [
        "import LeanFinance.Epistemic.FiniteSynthesisCompleteness",
        "",
        f"namespace {namespace}",
        "",
        "open LeanFinance.Epistemic",
        "",
        "/-- Generated by `python -m tools.workflow_cegis synth`. Do not edit by hand. -/",
        "",
    ]
    lines += _render_inductive(
        "History", [history_ident[history.id] for history in histories]
    )
    lines += _render_inductive(
        "Channel", [channel_ident[channel.id] for channel in channels]
    )
    lines += _render_inductive(
        "Observation", [observation_ident[value] for value in observation_values]
    )
    lines += [
        "def histories : List History :=",
        "  " + lean_list([f".{history_ident[history.id]}" for history in histories]),
        "",
        "def channels : List Channel :=",
        "  " + lean_list([f".{channel_ident[channel.id]}" for channel in channels]),
        "",
        "def observe : Channel → History → Observation",
    ]
    channel_data = {channel["id"]: channel for channel in evidence_model["channels"]}
    for channel in channels:
        for history in histories:
            encoded = canonical_dumps(
                channel_data[channel.id]["observations"][history.id]
            )
            lines.append(
                f"  | .{channel_ident[channel.id]}, .{history_ident[history.id]} => .{observation_ident[encoded]}"
            )
    lines += ["", "def claim : History → Bool"]
    for history in histories:
        lines.append(
            f"  | .{history_ident[history.id]} => {'true' if history.claim else 'false'}"
        )
    lines += ["", "def cost : Channel → Nat"]
    for channel in channels:
        lines.append(
            f"  | .{channel_ident[channel.id]} => {channel.weighted_cost(model.cost_weights)}"
        )
    lines += [
        "",
        "def model : BoundedEvidenceModel History Channel Observation :=",
        "  {",
        "    histories := histories",
        "    channels := channels",
        "    observe := observe",
        "    claim := claim",
        "    cost := cost",
        "  }",
        "",
        f"abbrev Candidate := Fin {candidate_count}",
        "",
        "/-- Bit `index` selects one channel in the fixed generated ordering. -/",
        "def bitSelected (mask index : Nat) : Bool :=",
        "  ((mask / (2 ^ index)) % 2) == 1",
        "",
        "def decodeMask (mask : Nat) : List Channel :=",
    ]
    for index, channel in enumerate(channels):
        prefix = "  " if index == 0 else "    ++ "
        fragment = (
            f"(if bitSelected mask {index} then "
            f"[.{channel_ident[channel.id]}] else [])"
        )
        lines.append(prefix + fragment)
    lines += [
        "",
        "def decode (candidate : Candidate) : List Channel :=",
        "  decodeMask candidate.val",
        "",
        "def selected : Candidate :=",
        f"  ⟨{selected_mask}, by decide⟩",
        "",
        "theorem selectedBoundedlyVerifies :",
        "    BoundedSelectionVerifies model (decode selected) := by",
        "  apply boundedVerifiesBool_sound",
        "  decide",
        "",
        "/-- Kernel computation checks all generated channel subsets, rather than",
        "    trusting the external optimizer's reported minimum. -/",
        "theorem checkerAcceptedCostMinimal :",
        "    ∀ candidate : Candidate,",
        "      boundedVerifiesBool model (decode candidate) = true →",
        "        selectionCost model (decode selected) ≤",
        "          selectionCost model (decode candidate) := by",
        "  decide",
        "",
        "theorem synthesized_selection_semantically_verifies :",
        "    ChannelSelectionVerifies",
        "      model.observe",
        "      (fun evidenceChannel => evidenceChannel ∈ decode selected)",
        "      model.ClaimHolds :=",
        "  bounded_verification_semantically_sound",
        "    model (decode selected)",
        "    (by intro history; cases history <;> simp [model, histories])",
        "    selectedBoundedlyVerifies",
        "",
        "theorem synthesized_selection_is_cost_minimal",
        "    (candidate : Candidate)",
        "    (candidateVerifies :",
        "      BoundedSelectionVerifies model (decode candidate)) :",
        "    selectionCost model (decode selected) ≤",
        "      selectionCost model (decode candidate) :=",
        "  checkerAcceptedCostMinimal candidate",
        "    (boundedVerifiesBool_complete model (decode candidate)",
        "      candidateVerifies)",
        "",
        f"end {namespace}",
        "",
    ]
    return "\n".join(lines)
