from __future__ import annotations

from .expr import lean_expr
from .explore import ExpandedChannel, History
from .model import WorkflowModel
from .lean_common import _render_inductive, lean_list, unique_identifiers


def render_workflow_lean(
    model: WorkflowModel,
    histories: tuple[History, ...],
    channels: tuple[ExpandedChannel, ...],
) -> str:
    variable_ident = unique_identifiers(
        [variable.id for variable in model.variables], "field"
    )
    action_ident = unique_identifiers([action.id for action in model.actions], "action")
    sensor_ident = unique_identifiers([channel.id for channel in channels], "sensor")
    namespace = model.workflow_namespace
    lines: list[str] = [
        "import LeanFinance.Epistemic.WorkflowTransition",
        "",
        f"namespace {namespace}",
        "",
        "open LeanFinance.Epistemic",
        "",
        "/-- Generated by `python -m tools.workflow_cegis synth`. Do not edit by hand. -/",
        "",
        "structure State where",
    ]
    for variable in model.variables:
        lines.append(f"  {variable_ident[variable.id]} : Bool")
    lines += ["  deriving Repr, DecidableEq", ""]
    lines += _render_inductive(
        "Action", [action_ident[action.id] for action in model.actions]
    )
    lines += _render_inductive(
        "Sensor", [sensor_ident[channel.id] for channel in channels]
    )
    lines += [
        "structure RawObservation where",
        "  actions : List Action",
        "  state : List Bool",
        "  deriving Repr, DecidableEq",
        "",
        "def initialState : State :=",
        "  {",
    ]
    for variable in model.variables:
        value = "true" if variable.initial else "false"
        lines.append(f"    {variable_ident[variable.id]} := {value}")
    lines += ["  }", "", "def enabled (state : State) (trace : List Action) : Action → Bool"]
    for action in model.actions:
        action_name = action_ident[action.id]
        guard = lean_expr(action.guard)
        lines += [
            f"  | .{action_name} =>",
            f"      ({guard}) && decide (trace.count .{action_name} < {action.max_occurrences})",
        ]
    lines += ["", "def transition (state : State) : Action → State"]
    for action in model.actions:
        action_name = action_ident[action.id]
        lines += [f"  | .{action_name} =>", "      { state with"]
        for effect in action.effects:
            lines.append(
                f"        {variable_ident[effect.variable]} := {lean_expr(effect.value)}"
            )
        lines += ["      }"]
    lines += [
        "",
        "def terminal (state : State) : Bool :=",
        f"  {lean_expr(model.terminal)}",
        "",
        "def claimState (state : State) : Bool :=",
        f"  {lean_expr(model.claim)}",
        "",
        "def workflow : FiniteWorkflow State Action :=",
        "  {",
        "    initial := initialState",
        "    actions := "
        + lean_list([f".{action_ident[action.id]}" for action in model.actions]),
        "    enabled := enabled",
        "    transition := transition",
        "    terminal := terminal",
        "  }",
        "",
        f"def maxDepth : Nat := {model.max_depth}",
        "",
        "def traceClaim (trace : List Action) : Bool :=",
        "  match replay workflow trace with",
        "  | some state => claimState state",
        "  | none => false",
        "",
        "def visibleAction : Sensor → Action → Bool",
    ]
    for channel in channels:
        sensor = sensor_ident[channel.id]
        visible = set(channel.visible_actions)
        for action in model.actions:
            action_name = action_ident[action.id]
            value = "true" if action.id in visible else "false"
            lines.append(f"  | .{sensor}, .{action_name} => {value}")
    lines += ["", "def stateProjection : Sensor → State → List Bool"]
    for channel in channels:
        sensor = sensor_ident[channel.id]
        values = [f"state.{variable_ident[field]}" for field in channel.visible_state]
        lines.append(f"  | .{sensor}, state => {lean_list(values)}")
    lines += [
        "",
        "def projectTrace (sensor : Sensor) (trace : List Action) : RawObservation :=",
        "  {",
        "    actions := trace.filter (visibleAction sensor)",
        "    state :=",
        "      match replay workflow trace with",
        "      | some state => stateProjection sensor state",
        "      | none => []",
        "  }",
        "",
        "def generatedTraces : List (List Action) :=",
        "  " + lean_list(
            [
                lean_list([f".{action_ident[action_id]}" for action_id in history.trace])
                for history in histories
            ]
        ),
        "",
        "theorem generated_traces_complete :",
        "    generatedTraces = enumerateTerminalTraces workflow maxDepth := by",
        "  decide",
        "",
        f"end {namespace}",
        "",
    ]
    return "\n".join(lines)
