from __future__ import annotations

import re
from typing import Any, Iterable

from .errors import ValidationError

_LEAN_KEYWORDS = {
    "abbrev",
    "axiom",
    "by",
    "class",
    "def",
    "deriving",
    "do",
    "else",
    "end",
    "example",
    "export",
    "extends",
    "false",
    "forall",
    "fun",
    "if",
    "import",
    "in",
    "inductive",
    "infix",
    "instance",
    "let",
    "match",
    "namespace",
    "open",
    "opaque",
    "private",
    "protected",
    "structure",
    "syntax",
    "theorem",
    "true",
    "universe",
    "variable",
    "where",
    "with",
}


def lean_identifier(value: str, *, prefix: str = "v") -> str:
    identifier = re.sub(r"[^A-Za-z0-9_]", "_", value)
    identifier = re.sub(r"_+", "_", identifier).strip("_")
    if not identifier:
        identifier = prefix
    if identifier[0].isdigit():
        identifier = f"{prefix}_{identifier}"
    if identifier in _LEAN_KEYWORDS:
        identifier = f"{prefix}_{identifier}"
    return identifier


def lean_string(value: str) -> str:
    if not isinstance(value, str):
        raise ValidationError("Lean string value must be a string")
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    if any(ord(char) < 0x20 for char in escaped if char not in "\n\r\t"):
        raise ValidationError("unsupported control character in Lean string")
    return f'"{escaped}"'


def _algorithm(value: str) -> str:
    mapping = {"sha256": ".sha256", "sha512": ".sha512", "blake3": ".blake3"}
    try:
        return mapping[value]
    except KeyError as exc:
        raise ValidationError(f"unsupported Lean hash algorithm: {value}") from exc


def _list(values: Iterable[str]) -> str:
    return "[" + ", ".join(values) + "]"


def _artifact_def(name: str, kind: str, ref: dict[str, str]) -> list[str]:
    return [
        f"def {name} : ArtifactRef .{kind} :=",
        f"  {{ algorithm := {_algorithm(ref['algorithm'])}",
        f"    schemaId := {lean_string(ref['schema_id'])}",
        f"    digest := {lean_string(ref['digest'])} }}",
        "",
    ]


def _membership_case_header(
    *, variable: str, owner: str, count: int, indent: str = "    "
) -> list[str]:
    if count == 0:
        return [f"{indent}simpa [{owner}] using used"]
    if count == 1:
        return [
            f"{indent}have usedEq : {variable} = _ := by simpa [{owner}] using used",
            f"{indent}subst {variable}",
        ]
    alternatives = " | ".join("rfl" for _ in range(count))
    return [
        f"{indent}simp only [{owner}, List.mem_cons, List.mem_singleton] at used",
        f"{indent}rcases used with {alternatives}",
    ]


def _member_proof_header(
    *, variable: str, definitions: list[str], count: int, indent: str = "  "
) -> list[str]:
    defs = ", ".join(definitions)
    if count == 1:
        return [
            f"{indent}have memberEq : {variable} = _ := by simpa [{defs}] using member",
            f"{indent}subst {variable}",
        ]
    alternatives = " | ".join("rfl" for _ in range(count))
    return [
        f"{indent}simp only [{defs}, List.mem_cons, List.mem_singleton] at member",
        f"{indent}rcases member with {alternatives}",
    ]


def render_lean(bundle: dict[str, Any]) -> str:
    experiment = bundle["experiment"]
    namespace = experiment["lean_namespace"]
    artifacts = bundle["artifacts"]
    decision_data = bundle["decision"]
    claim_data = bundle["claim"]
    ledger_data = bundle["ledger"]
    anchor_data = bundle["anchor"]

    dataset_entries = artifacts["datasets"]
    feature_entries = artifacts["features"]
    dataset_by_id = {entry["id"]: entry for entry in dataset_entries}
    feature_by_name = {entry["name"]: entry for entry in feature_entries}

    dataset_ident: dict[str, str] = {}
    feature_ident: dict[str, str] = {}
    used_identifiers: set[str] = set()

    def unique(base: str) -> str:
        candidate = base
        counter = 2
        while candidate in used_identifiers:
            candidate = f"{base}_{counter}"
            counter += 1
        used_identifiers.add(candidate)
        return candidate

    for entry in dataset_entries:
        dataset_ident[entry["id"]] = unique(lean_identifier(entry["id"], prefix="dataset"))
    for entry in feature_entries:
        feature_ident[entry["name"]] = unique(lean_identifier(entry["name"], prefix="feature"))

    lines: list[str] = [
        "import LeanFinance.Backtest.AdapterContract",
        "",
        f"namespace {namespace}",
        "",
        "open LeanFinance.Backtest",
        "",
        "/-- Generated by `python -m tools.lfv_adapter build`. Do not edit by hand. -/",
        "",
    ]

    code_ref = artifacts["code"]["ref"]
    parameter_ref = artifacts["parameters"]["ref"]
    environment_ref = artifacts["environment"]["ref"]
    result_ref = artifacts["result"]["ref"]
    lines += _artifact_def("codeArtifact", "sourceCode", code_ref)
    lines += _artifact_def("parameterArtifact", "parameterSet", parameter_ref)
    lines += _artifact_def("environmentArtifact", "environment", environment_ref)
    lines += _artifact_def("resultArtifact", "result", result_ref)

    for entry in dataset_entries:
        ident = dataset_ident[entry["id"]]
        lines += _artifact_def(f"datasetArtifact_{ident}", "dataset", entry["artifact"]["ref"])
    for entry in feature_entries:
        ident = feature_ident[entry["name"]]
        lines += _artifact_def(f"featureArtifact_{ident}", "feature", entry["artifact"]["ref"])

    # Historical trial artifacts that are not definitionally the current code/parameters.
    trial_code_names: list[str] = []
    trial_parameter_names: list[str] = []
    trial_commitment_names: list[str] = []
    for index, entry in enumerate(ledger_data["entries"]):
        code_name = "codeArtifact"
        parameter_name = "parameterArtifact"
        if entry["code"] != code_ref:
            code_name = f"trialCode_{index}"
            lines += _artifact_def(code_name, "sourceCode", entry["code"])
        if entry["parameters"] != parameter_ref:
            parameter_name = f"trialParameters_{index}"
            lines += _artifact_def(parameter_name, "parameterSet", entry["parameters"])
        commitment_name = f"trialCommitment_{index}"
        lines += _artifact_def(commitment_name, "searchLedger", entry["commitment"])
        trial_code_names.append(code_name)
        trial_parameter_names.append(parameter_name)
        trial_commitment_names.append(commitment_name)

    for entry in dataset_entries:
        ident = dataset_ident[entry["id"]]
        lines += [
            f"def dataset_{ident} : Dataset :=",
            f"  {{ id := {lean_string(entry['id'])}",
            f"    observedAt := {entry['observed_at']}",
            f"    availableAt := {entry['available_at']}",
            f"    contentHash := datasetArtifact_{ident}.digest }}",
            "",
        ]

    for entry in feature_entries:
        ident = feature_ident[entry["name"]]
        input_hashes: list[str] = []
        for reference in entry["inputs"]:
            kind, _, target = reference.partition(":")
            if kind == "dataset":
                dep = dataset_ident[target]
                input_hashes.append(f"dataset_{dep}.contentHash")
            else:
                dep = feature_ident[target]
                input_hashes.append(f"featureArtifact_{dep}.digest")
        lines += [
            f"def featureLineage_{ident} : FeatureLineage :=",
            f"  {{ featureName := {lean_string(entry['name'])}",
            f"    inputHashes := {_list(input_hashes)}",
            f"    generatedAt := {entry['generated_at']}",
            "    codeHash := codeArtifact.digest }",
            "",
            f"def derivedFeature_{ident} : DerivedFeature :=",
            f"  {{ outputHash := featureArtifact_{ident}.digest",
            f"    lineage := featureLineage_{ident} }}",
            "",
        ]

    all_dataset_defs = [f"dataset_{dataset_ident[entry['id']]}" for entry in dataset_entries]
    all_feature_defs = [f"derivedFeature_{feature_ident[entry['name']]}" for entry in feature_entries]
    lines += [
        "def lineageCatalog : LineageCatalog :=",
        f"  {{ datasets := {_list(all_dataset_defs)}",
        f"    features := {_list(all_feature_defs)} }}",
        "",
    ]

    used_dataset_defs = [f"dataset_{dataset_ident[item['id']]}" for item in decision_data["datasets"]]
    used_feature_lineages = [
        f"featureLineage_{feature_ident[item['name']]}" for item in decision_data["features"]
    ]
    manifest_dataset_artifacts = [
        f"datasetArtifact_{dataset_ident[item['id']]}" for item in decision_data["datasets"]
    ]
    lines += [
        "def decision : Decision :=",
        f"  {{ strategyId := {lean_string(decision_data['strategy_id'])}",
        f"    decisionTime := {decision_data['decision_time']}",
        f"    datasets := {_list(used_dataset_defs)}",
        f"    features := {_list(used_feature_lineages)}",
        "    parameterHash := parameterArtifact.digest }",
        "",
        "def manifest : BoundExperimentManifest :=",
        f"  {{ name := {lean_string(experiment['name'])}",
        "    code := codeArtifact",
        f"    datasets := {_list(manifest_dataset_artifacts)}",
        "    parameters := parameterArtifact",
        "    environment := environmentArtifact",
        "    result := resultArtifact }",
        "",
    ]

    for index, entry in enumerate(ledger_data["entries"]):
        previous = "none" if index == 0 else f"some trialCommitment_{index - 1}"
        lines += [
            f"def trial_{index} : RegisteredTrial :=",
            f"  {{ hypothesisId := {lean_string(entry['hypothesis_id'])}",
            f"    parameters := {trial_parameter_names[index]}",
            f"    code := {trial_code_names[index]}",
            f"    registeredAt := {entry['registered_at']}",
            f"    previousCommitment := {previous}",
            f"    commitment := {trial_commitment_names[index]} }}",
            "",
        ]
    lines += [
        "def ledger : CommittedSearchLedger :=",
        f"  {{ entries := {_list([f'trial_{i}' for i in range(len(ledger_data['entries']))])} }}",
        "",
        "def ledgerAnchor : LedgerAnchor :=",
        f"  {{ commitment := trialCommitment_{len(ledger_data['entries']) - 1}",
        f"    entryCount := {anchor_data['entry_count']}",
        f"    anchoredAt := {anchor_data['anchored_at']} }}",
        "",
        "def claim : BacktestClaim :=",
        "  { decision := decision",
        "    resultHash := resultArtifact.digest",
        f"    metricName := {lean_string(claim_data['metric_name'])}",
        f"    metricValue := {claim_data['metric_value']} }}",
        "",
    ]

    manifest_defs = [
        "StronglyReproducible",
        "manifest",
        "ArtifactRef.Valid",
        "NonEmptyString",
        "codeArtifact",
        "parameterArtifact",
        "environmentArtifact",
        "resultArtifact",
    ] + [f"datasetArtifact_{dataset_ident[item['id']]}" for item in decision_data["datasets"]]
    lines += [
        "theorem manifestBound : StronglyReproducible manifest := by",
        f"  simp [{', '.join(manifest_defs)}]",
        "",
    ]

    # Availability at each feature's own generation timestamp, which prevents
    # an input produced later from justifying an earlier feature.
    for entry in feature_entries:
        ident = feature_ident[entry["name"]]
        lines += [
            f"theorem featureAvailableAtGeneration_{ident} :",
            f"    ArtifactAvailableAt lineageCatalog featureLineage_{ident}.generatedAt",
            f"      derivedFeature_{ident}.outputHash := by",
            f"  apply ArtifactAvailableAt.feature derivedFeature_{ident}",
            "  · simp [lineageCatalog]",
            f"  · simp [derivedFeature_{ident}, featureArtifact_{ident}, NonEmptyString]",
            f"  · simp [FeatureAvailableAt, derivedFeature_{ident}, featureLineage_{ident}]",
            f"  · simp [FeatureBoundToInputs, derivedFeature_{ident}, featureLineage_{ident},",
            "      codeArtifact, NonEmptyString]",
            "  · intro inputHash member",
        ]
        inputs = entry["inputs"]
        if len(inputs) == 1:
            only_kind, _, only_target = inputs[0].partition(":")
            if only_kind == "dataset":
                only_dep = dataset_ident[only_target]
                only_expression = f"dataset_{only_dep}.contentHash"
            else:
                only_dep = feature_ident[only_target]
                only_expression = f"featureArtifact_{only_dep}.digest"
            lines += [
                f"    have memberEq : inputHash = {only_expression} := by",
                f"      simpa [derivedFeature_{ident}, featureLineage_{ident}] using member",
                "    subst inputHash",
            ]
        else:
            lines += _member_proof_header(
                variable="inputHash",
                definitions=[f"derivedFeature_{ident}", f"featureLineage_{ident}"],
                count=len(inputs),
                indent="    ",
            )
        for reference in inputs:
            kind, _, target = reference.partition(":")
            if len(inputs) > 1:
                first_prefix = "    · "
                continuation = "      "
            else:
                first_prefix = "    "
                continuation = "    "
            if kind == "dataset":
                dep = dataset_ident[target]
                lines += [
                    f"{first_prefix}apply ArtifactAvailableAt.dataset dataset_{dep}",
                    f"{continuation}· simp [lineageCatalog]",
                    f"{continuation}· simp [DatasetAvailableAt, dataset_{dep}, featureLineage_{ident}]",
                    f"{continuation}· simp [DatasetHashBound, dataset_{dep}, datasetArtifact_{dep},",
                    f"{continuation}    NonEmptyString]",
                ]
            else:
                dep = feature_ident[target]
                lines += [
                    f"{first_prefix}apply ArtifactAvailableAt.mono featureAvailableAtGeneration_{dep}",
                    f"{continuation}simp [featureLineage_{dep}, featureLineage_{ident}]",
                ]
        lines += [
            "",
            f"theorem featureAvailableAtDecision_{ident} :",
            f"    ArtifactAvailableAt lineageCatalog decision.decisionTime",
            f"      derivedFeature_{ident}.outputHash := by",
            f"  apply ArtifactAvailableAt.mono featureAvailableAtGeneration_{ident}",
            f"  simp [featureLineage_{ident}, decision]",
            "",
        ]

    lines += ["theorem noFutureInformation : NoFutureInformation decision := by", "  constructor"]
    used_datasets = decision_data["datasets"]
    lines += ["  · intro dataset used"]
    if len(used_datasets) == 0:
        lines += ["    simpa [decision] using used"]
    elif len(used_datasets) == 1:
        target = dataset_ident[used_datasets[0]["id"]]
        lines += [
            f"    have usedEq : dataset = dataset_{target} := by simpa [decision] using used",
            "    subst dataset",
            f"    simp [DatasetAvailableAt, dataset_{target}, decision]",
        ]
    else:
        lines += [
            "    simp only [decision, List.mem_cons, List.mem_singleton] at used",
            "    rcases used with " + " | ".join("rfl" for _ in used_datasets),
        ]
        for item in used_datasets:
            target = dataset_ident[item["id"]]
            lines += [f"    · simp [DatasetAvailableAt, dataset_{target}, decision]"]
    used_features = decision_data["features"]
    lines += ["  · intro feature used"]
    if len(used_features) == 0:
        lines += ["    simpa [decision] using used"]
    elif len(used_features) == 1:
        target = feature_ident[used_features[0]["name"]]
        lines += [
            f"    have usedEq : feature = featureLineage_{target} := by simpa [decision] using used",
            "    subst feature",
            f"    simp [FeatureAvailableAt, featureLineage_{target}, decision]",
        ]
    else:
        lines += [
            "    simp only [decision, List.mem_cons, List.mem_singleton] at used",
            "    rcases used with " + " | ".join("rfl" for _ in used_features),
        ]
        for item in used_features:
            target = feature_ident[item["name"]]
            lines += [f"    · simp [FeatureAvailableAt, featureLineage_{target}, decision]"]
    lines.append("")

    lines += [
        "theorem lineageClosed : DecisionLineageClosed lineageCatalog decision := by",
        "  intro lineage used",
    ]
    if len(used_features) == 0:
        lines += ["  simpa [decision] using used"]
    elif len(used_features) == 1:
        target = feature_ident[used_features[0]["name"]]
        lines += [
            f"  have usedEq : lineage = featureLineage_{target} := by simpa [decision] using used",
            "  subst lineage",
            f"  exact ⟨derivedFeature_{target}, by simp [lineageCatalog], rfl,",
            f"    featureAvailableAtDecision_{target}⟩",
        ]
    else:
        lines += [
            "  simp only [decision, List.mem_cons, List.mem_singleton] at used",
            "  rcases used with " + " | ".join("rfl" for _ in used_features),
        ]
        for item in used_features:
            target = feature_ident[item["name"]]
            lines += [
                f"  · exact ⟨derivedFeature_{target}, by simp [lineageCatalog], rfl,",
                f"      featureAvailableAtDecision_{target}⟩",
            ]
    lines.append("")

    ledger_defs = [
        "CommittedSearchLedger.Valid",
        "ValidCommittedChain",
        "ValidCommittedSuffix",
        "LedgerLinks",
        "ledger",
        "RegisteredTrial.Bound",
        "ArtifactRef.Valid",
        "NonEmptyString",
        "codeArtifact",
        "parameterArtifact",
    ]
    ledger_defs += [f"trial_{i}" for i in range(len(ledger_data["entries"]))]
    ledger_defs += trial_code_names + trial_parameter_names + trial_commitment_names
    ledger_defs = list(dict.fromkeys(ledger_defs))
    lines += [
        "theorem ledgerValid : ledger.Valid := by",
        f"  simp [{', '.join(ledger_defs)}]",
        "",
        "theorem ledgerAnchored : AnchorsLedger ledgerAnchor ledger := by",
        "  simp [AnchorsLedger, ledgerAnchor, ledger, lastCommitment,",
        f"    {', '.join([f'trial_{i}' for i in range(len(ledger_data['entries']))])},",
        f"    {', '.join(trial_commitment_names)}, ArtifactRef.Valid, NonEmptyString]",
        "",
        "theorem anchorAvailable : AnchorAvailableAt ledgerAnchor decision := by",
        "  simp [AnchorAvailableAt, ledgerAnchor, decision]",
        "",
    ]

    selected_index = bundle["selected_trial_index"]
    lines += [
        "def certificate : ProofCarryingBacktestCertificate claim :=",
        "  { manifest := manifest",
        "    ledger := ledger",
        "    ledgerAnchor := ledgerAnchor",
        "    lineageCatalog := lineageCatalog",
        "    manifestBound := manifestBound",
        "    resultBound := rfl",
        "    parameterBound := rfl",
        "    dataBound := by",
        "      intro dataset used",
    ]
    if len(used_datasets) == 1:
        target = dataset_ident[used_datasets[0]["id"]]
        lines += [
            f"      have usedEq : dataset = dataset_{target} := by simpa [claim, decision] using used",
            "      subst dataset",
            f"      exact ⟨datasetArtifact_{target}, by simp [manifest], rfl⟩",
        ]
    else:
        lines += [
            "      simp only [claim, decision, List.mem_cons, List.mem_singleton] at used",
            "      rcases used with " + " | ".join("rfl" for _ in used_datasets),
        ]
        for item in used_datasets:
            target = dataset_ident[item["id"]]
            lines += [
                f"      · exact ⟨datasetArtifact_{target}, by simp [manifest], rfl⟩"
            ]
    lines += [
        "    noFutureInformation := noFutureInformation",
        "    lineageClosed := lineageClosed",
        "    ledgerValid := ledgerValid",
        "    ledgerAnchored := ledgerAnchored",
        "    anchorAvailable := anchorAvailable",
        "    selectedTrialPreRegistered := by",
        f"      refine ⟨trial_{selected_index}, ?_, rfl, rfl, rfl, ?_⟩",
        "      · simp [ledger]",
        f"      · simp [trial_{selected_index}, claim, decision] }}",
        "",
        "def executionRecord : AdapterExecutionRecord :=",
        "  { claim := claim",
        "    certificate := certificate }",
        "",
        "def certifiedOutput : CertifiedAdapterOutput :=",
        "  { record := executionRecord",
        "    valid := by rfl }",
        "",
        "theorem generated_output_preserves_result_binding :",
        "    certifiedOutput.record.certificate.manifest.result.digest =",
        "      certifiedOutput.record.claim.resultHash :=",
        "  adapter_preserves_result_binding certifiedOutput",
        "",
        f"end {namespace}",
        "",
    ]
    return "\n".join(lines)
