from __future__ import annotations

import re
from typing import Any

from tools.evidence_synth.canonical import canonical_dumps

from .model import RobustEvidenceModel

_LEAN_KEYWORDS = {
    "abbrev",
    "axiom",
    "by",
    "class",
    "def",
    "deriving",
    "do",
    "else",
    "end",
    "example",
    "export",
    "extends",
    "false",
    "forall",
    "fun",
    "if",
    "import",
    "in",
    "inductive",
    "infix",
    "instance",
    "let",
    "match",
    "namespace",
    "open",
    "opaque",
    "private",
    "protected",
    "structure",
    "syntax",
    "theorem",
    "true",
    "universe",
    "variable",
    "where",
    "with",
}


def lean_identifier(value: str, *, prefix: str) -> str:
    identifier = re.sub(r"[^A-Za-z0-9_]", "_", value)
    identifier = re.sub(r"_+", "_", identifier).strip("_")
    if not identifier:
        identifier = prefix
    identifier = identifier[0].lower() + identifier[1:]
    if identifier[0].isdigit():
        identifier = f"{prefix}_{identifier}"
    if identifier in _LEAN_KEYWORDS:
        identifier = f"{prefix}_{identifier}"
    return identifier


def unique_identifiers(values: list[str], prefix: str) -> dict[str, str]:
    used: set[str] = set()
    result: dict[str, str] = {}
    for value in values:
        base = lean_identifier(value, prefix=prefix)
        candidate = base
        counter = 2
        while candidate in used:
            candidate = f"{base}_{counter}"
            counter += 1
        used.add(candidate)
        result[value] = candidate
    return result


def lean_list(items: list[str]) -> str:
    return "[" + ", ".join(items) + "]"


def render_inductive(name: str, constructors: list[str]) -> list[str]:
    lines = [f"inductive {name} where"]
    lines.extend(f"  | {constructor}" for constructor in constructors)
    lines.append("  deriving Repr, DecidableEq")
    lines.append("")
    return lines


def render_lean(
    model: RobustEvidenceModel, certificate: dict[str, Any]
) -> str:
    if certificate["status"] != "synthesized":
        raise ValueError("Lean witness generation requires a synthesized model")
    history_ids = [history.id for history in model.histories]
    channel_ids = [channel.id for channel in model.channels]
    history_ident = unique_identifiers(history_ids, "history")
    channel_ident = unique_identifiers(channel_ids, "channel")
    domain_ident = unique_identifiers(list(model.domains), "domain")

    observation_values: list[str] = []
    for channel in model.channels:
        for history in model.histories:
            encoded = canonical_dumps(channel.observations[history.id])
            if encoded not in observation_values:
                observation_values.append(encoded)
    observation_ident = {
        encoded: f"obs{index}"
        for index, encoded in enumerate(observation_values)
    }

    candidate_count = 1 << len(model.channels)
    selected_mask = certificate["selected"]["mask"]
    lines: list[str] = [
        "import LeanFinance.Epistemic.FiniteRobustSynthesis",
        "",
        f"namespace {model.namespace}",
        "",
        "open LeanFinance.Epistemic",
        "",
        "/-- Generated by `python -m tools.robust_evidence_synth synth`. -/",
        "",
    ]
    lines += render_inductive(
        "History", [history_ident[value] for value in history_ids]
    )
    lines += render_inductive(
        "Channel", [channel_ident[value] for value in channel_ids]
    )
    lines += render_inductive(
        "Domain", [domain_ident[value] for value in model.domains]
    )
    lines += render_inductive(
        "Observation", [observation_ident[value] for value in observation_values]
    )
    lines += [
        "def histories : List History :=",
        "  "
        + lean_list([f".{history_ident[value]}" for value in history_ids]),
        "",
        "def channels : List Channel :=",
        "  "
        + lean_list([f".{channel_ident[value]}" for value in channel_ids]),
        "",
        "def observe : Channel → History → Observation",
    ]
    for channel in model.channels:
        for history in model.histories:
            encoded = canonical_dumps(channel.observations[history.id])
            lines.append(
                f"  | .{channel_ident[channel.id]}, "
                f".{history_ident[history.id]} => "
                f".{observation_ident[encoded]}"
            )
    lines += ["", "def claim : History → Bool"]
    for history in model.histories:
        lines.append(
            f"  | .{history_ident[history.id]} => "
            f"{'true' if history.claim else 'false'}"
        )
    lines += ["", "def cost : Channel → Nat"]
    for channel in model.channels:
        lines.append(
            f"  | .{channel_ident[channel.id]} => "
            f"{model.weighted_channel_cost(channel.id)}"
        )
    lines += ["", "def trustDomain : Channel → Domain"]
    for channel in model.channels:
        lines.append(
            f"  | .{channel_ident[channel.id]} => "
            f".{domain_ident[channel.domain]}"
        )
    lines += [
        "",
        "def model : BoundedEvidenceModel History Channel Observation :=",
        "  {",
        "    histories := histories",
        "    channels := channels",
        "    observe := observe",
        "    claim := claim",
        "    cost := cost",
        "  }",
        "",
        "def faults : List (List Domain) :=",
        "  "
        + lean_list(
            [
                lean_list([f".{domain_ident[value]}" for value in fault])
                for fault in certificate["faults"]
            ]
        ),
        "",
        f"abbrev Candidate := Fin {candidate_count}",
        "",
        "def bitSelected (mask index : Nat) : Bool :=",
        "  ((mask / (2 ^ index)) % 2) == 1",
        "",
        "def decodeMask (mask : Nat) : List Channel :=",
    ]
    for index, channel in enumerate(model.channels):
        prefix = "  " if index == 0 else "    ++ "
        lines.append(
            prefix
            + f"(if bitSelected mask {index} then "
            + f"[.{channel_ident[channel.id]}] else [])"
        )
    lines += [
        "",
        "def decode (candidate : Candidate) : List Channel :=",
        "  decodeMask candidate.val",
        "",
        "def selected : Candidate :=",
        f"  ⟨{selected_mask}, by decide⟩",
        "",
        "theorem selectedBoundedlyRobust :",
        "    BoundedRobustSelectionVerifies",
        "      model trustDomain faults (decode selected) := by",
        "  apply boundedRobustVerifiesBool_sound",
        "  decide",
        "",
        "theorem checkerAcceptedCostMinimal :",
        "    ∀ candidate : Candidate,",
        "      boundedRobustVerifiesBool",
        "          model trustDomain (decode candidate) faults = true →",
        "        selectionCost model (decode selected) ≤",
        "          selectionCost model (decode candidate) := by",
        "  decide",
        "",
        "def synthesisCertificate :",
        "    BoundedRobustSynthesisCertificate",
        "      model trustDomain faults Candidate decode selected :=",
        "  {",
        "    selectedVerifies := selectedBoundedlyRobust",
        "    minimum := by",
        "      intro candidate candidateVerifies",
        "      exact checkerAcceptedCostMinimal candidate",
        "        (boundedRobustVerifiesBool_complete",
        "          model trustDomain faults (decode candidate)",
        "          candidateVerifies)",
        "  }",
        "",
        "theorem selectedCostMinimal",
        "    (candidate : Candidate)",
        "    (candidateVerifies :",
        "      BoundedRobustSelectionVerifies",
        "        model trustDomain faults (decode candidate)) :",
        "    selectionCost model (decode selected) ≤",
        "      selectionCost model (decode candidate) :=",
        "  synthesisCertificate.selectedCostMinimal",
        "    candidate candidateVerifies",
        "",
    ]
    if model.required_connectivity == 2:
        lines += [
            "theorem faultsComplete :",
            "    FaultListComplete",
            "      (fun failedDomains : List Domain =>",
            "        failedDomains.Nodup ∧ failedDomains.length < 2)",
            "      faults := by",
            "  intro failedDomains allowed",
            "  cases failedDomains with",
            "  | nil =>",
            "      simp [faults]",
            "  | cons head tail =>",
            "      cases tail with",
            "      | nil =>",
            "          cases head <;> simp [faults]",
            "      | cons second rest =>",
            "          exfalso",
            "          exact (Nat.not_lt_of_ge (by simp)) allowed.2",
            "",
            "theorem selectedTrustDomainConnectivity :",
            "    TrustDomainConnectivityAtLeast",
            "      model.observe",
            "      (fun channel => channel ∈ decode selected)",
            "      model.ClaimHolds trustDomain 2 :=",
            "  boundedRobust_semantically_sound",
            "    model trustDomain faults (decode selected)",
            "    (fun failedDomains : List Domain =>",
            "      failedDomains.Nodup ∧ failedDomains.length < 2)",
            "    (by intro history; cases history <;> simp [model, histories])",
            "    faultsComplete selectedBoundedlyRobust",
            "",
        ]
    lines += [f"end {model.namespace}", ""]
    return "\n".join(lines)
