namespace LeanFinance.Epistemic

universe u v w

/-- One deterministic hypothesis for an action's enablement and state update. -/
structure ActionSemanticsHypothesis (State : Type u) where
  enabled : State → Bool
  transition : State → State

/-- A positive observation records a pre-state where the action occurred and
    the observed post-state. -/
structure PositiveActionObservation (State : Type u) where
  before : State
  after : State

/-- A negative probe records a state where the action was observed or required
    to be disabled. -/
structure NegativeActionObservation (State : Type u) where
  state : State

/-- One action hypothesis explains one positive state transition. -/
def ConsistentWithPositive
    {State : Type u}
    (hypothesis : ActionSemanticsHypothesis State)
    (observation : PositiveActionObservation State) : Prop :=
  hypothesis.enabled observation.before = true ∧
    hypothesis.transition observation.before = observation.after

/-- One action hypothesis respects one negative enablement probe. -/
def ConsistentWithNegative
    {State : Type u}
    (hypothesis : ActionSemanticsHypothesis State)
    (observation : NegativeActionObservation State) : Prop :=
  hypothesis.enabled observation.state = false

/-- A hypothesis is in the version space generated by all positive and negative
    observations. -/
def ConsistentWithActionObservations
    {State : Type u}
    (positive : List (PositiveActionObservation State))
    (negative : List (NegativeActionObservation State))
    (hypothesis : ActionSemanticsHypothesis State) : Prop :=
  (∀ observation,
      observation ∈ positive →
        ConsistentWithPositive hypothesis observation) ∧
    (∀ observation,
      observation ∈ negative →
        ConsistentWithNegative hypothesis observation)

/-- Explicit finite version space selected from one candidate hypothesis list. -/
def ActionVersionSpace
    {State : Type u}
    (candidates : List (ActionSemanticsHypothesis State))
    (positive : List (PositiveActionObservation State))
    (negative : List (NegativeActionObservation State)) :
    ActionSemanticsHypothesis State → Prop :=
  fun hypothesis =>
    hypothesis ∈ candidates ∧
      ConsistentWithActionObservations positive negative hypothesis

/-- Observation-list inclusion. -/
def ObservationsIncluded
    {Observation : Type u}
    (small large : List Observation) : Prop :=
  ∀ observation,
    observation ∈ small → observation ∈ large

/-- **Version-space contraction.** Adding positive or negative observations can
    only remove action-semantics hypotheses. -/
theorem actionVersionSpace_antitone_under_observation_extension
    {State : Type u}
    (candidates : List (ActionSemanticsHypothesis State))
    (smallPositive largePositive :
      List (PositiveActionObservation State))
    (smallNegative largeNegative :
      List (NegativeActionObservation State))
    (positiveIncluded :
      ObservationsIncluded smallPositive largePositive)
    (negativeIncluded :
      ObservationsIncluded smallNegative largeNegative) :
    ∀ hypothesis,
      ActionVersionSpace candidates
          largePositive largeNegative hypothesis →
        ActionVersionSpace candidates
          smallPositive smallNegative hypothesis := by
  intro hypothesis largeConsistent
  refine ⟨largeConsistent.1, ?_⟩
  constructor
  · intro observation member
    exact largeConsistent.2.1 observation
      (positiveIncluded observation member)
  · intro observation member
    exact largeConsistent.2.2 observation
      (negativeIncluded observation member)

/-- Two hypotheses are observationally equivalent on one finite probe family
    when they predict equal enablement and, whenever enabled, equal next states. -/
def HypothesesEquivalentOn
    {State : Type u}
    (probes : List State)
    (left right : ActionSemanticsHypothesis State) : Prop :=
  ∀ state,
    state ∈ probes →
      left.enabled state = right.enabled state ∧
        (left.enabled state = true →
          left.transition state = right.transition state)

/-- One probe distinguishes two action hypotheses by enablement or by their
    enabled next-state predictions. -/
def ProbeSeparatesHypotheses
    {State : Type u}
    (probe : State)
    (left right : ActionSemanticsHypothesis State) : Prop :=
  left.enabled probe ≠ right.enabled probe ∨
    (left.enabled probe = true ∧
      right.enabled probe = true ∧
        left.transition probe ≠ right.transition probe)

/-- A probe that separates two currently consistent hypotheses is an active
    instrumentation candidate for contracting the version space. -/
structure DistinguishingProbe
    {State : Type u}
    (candidates : List (ActionSemanticsHypothesis State))
    (positive : List (PositiveActionObservation State))
    (negative : List (NegativeActionObservation State)) where
  probe : State
  left : ActionSemanticsHypothesis State
  right : ActionSemanticsHypothesis State
  leftConsistent :
    ActionVersionSpace candidates positive negative left
  rightConsistent :
    ActionVersionSpace candidates positive negative right
  separates : ProbeSeparatesHypotheses probe left right

namespace DistinguishingProbe

/-- A valid distinguishing probe proves that the current observation family has
    not identified one unique action semantics over the proposed probe space. -/
theorem witnesses_semantics_ambiguity
    {State : Type u}
    {candidates : List (ActionSemanticsHypothesis State)}
    {positive : List (PositiveActionObservation State)}
    {negative : List (NegativeActionObservation State)}
    (witness : DistinguishingProbe candidates positive negative) :
    witness.left ≠ witness.right := by
  intro sameHypothesis
  subst witness.right
  rcases witness.separates with enablementDifferent | transitionDifferent
  · exact enablementDifferent rfl
  · exact transitionDifferent.2.2 rfl

end DistinguishingProbe

/-- A model family indexed by hypotheses consistent with the observed traces. -/
def VersionSpaceAdmissibleWorld
    {State : Type u}
    {History : Type v}
    (candidates : List (ActionSemanticsHypothesis State))
    (positive : List (PositiveActionObservation State))
    (negative : List (NegativeActionObservation State))
    (historyAdmissible :
      ActionSemanticsHypothesis State → History → Prop) :
    ActionSemanticsHypothesis State → History → Prop :=
  fun hypothesis history =>
    ActionVersionSpace candidates positive negative hypothesis ∧
      historyAdmissible hypothesis history

end LeanFinance.Epistemic
