import LeanFinance.Epistemic.CutSet

namespace LeanFinance.Epistemic

universe u v w x

/-- One candidate semantics remains in the version space when it is consistent
    with every observed trace. -/
def VersionSpace
    {Model : Type u}
    {Trace : Type v}
    (consistent : Model → Trace → Prop)
    (observed : List Trace)
    (model : Model) : Prop :=
  ∀ trace,
    trace ∈ observed →
      consistent model trace

/-- Adding observations can only shrink the set of consistent semantics. -/
theorem version_space_antitone_in_traces
    {Model : Type u}
    {Trace : Type v}
    (consistent : Model → Trace → Prop)
    (older newer : List Trace)
    (contains : ∀ trace, trace ∈ older → trace ∈ newer)
    (model : Model)
    (consistentNewer : VersionSpace consistent newer model) :
    VersionSpace consistent older model := by
  intro trace member
  exact consistentNewer trace (contains trace member)

/-- A complete model/history world is admissible exactly when its semantics
    remains consistent with all observed traces. -/
def VersionSpaceWorld
    {Model : Type u}
    {Trace : Type v}
    {World : Type w}
    (consistent : Model → Trace → Prop)
    (observed : List Trace)
    (worldModel : World → Model)
    (world : World) : Prop :=
  VersionSpace consistent observed (worldModel world)

/-- Verification across every world generated by every still-consistent model. -/
def ModelFamilyVerifies
    {World : Type u}
    {Evidence : Type v}
    (observe : World → Evidence)
    (claim : World → Prop)
    (allowed : World → Prop) : Prop :=
  ∀ left right,
    allowed left →
      allowed right →
        observe left = observe right →
          (claim left ↔ claim right)

/-- Verification after committing to one particular semantics. -/
def PointModelVerifies
    {Model : Type u}
    {World : Type v}
    {Evidence : Type w}
    (worldModel : World → Model)
    (chosen : Model)
    (observe : World → Evidence)
    (claim : World → Prop)
    (allowed : World → Prop) : Prop :=
  ∀ left right,
    allowed left →
      allowed right →
        worldModel left = chosen →
          worldModel right = chosen →
            observe left = observe right →
              (claim left ↔ claim right)

/-- A model-family verifier is necessarily valid after restriction to any one
    member of the family. -/
theorem family_verification_implies_point_verification
    {Model : Type u}
    {World : Type v}
    {Evidence : Type w}
    (worldModel : World → Model)
    (chosen : Model)
    (observe : World → Evidence)
    (claim : World → Prop)
    (allowed : World → Prop)
    (familyVerified : ModelFamilyVerifies observe claim allowed) :
    PointModelVerifies worldModel chosen observe claim allowed := by
  intro left right leftAllowed rightAllowed _leftModel _rightModel sameEvidence
  exact familyVerified left right leftAllowed rightAllowed sameEvidence

/-- Constructive witness that a selected evidence map fails somewhere in the
    surviving model family. The worlds may come from different semantics, which
    is the key failure mode hidden by point refinement. -/
structure ModelFamilyCounterexample
    {Model : Type u}
    {World : Type v}
    {Evidence : Type w}
    (worldModel : World → Model)
    (observe : World → Evidence)
    (claim : World → Prop)
    (allowed : World → Prop) where
  left : World
  right : World
  leftAllowed : allowed left
  rightAllowed : allowed right
  sameEvidence : observe left = observe right
  leftClaim : claim left
  rightNotClaim : ¬ claim right
  semanticsDiffer : worldModel left ≠ worldModel right

namespace ModelFamilyCounterexample

theorem notFamilyVerifiable
    {Model : Type u}
    {World : Type v}
    {Evidence : Type w}
    {worldModel : World → Model}
    {observe : World → Evidence}
    {claim : World → Prop}
    {allowed : World → Prop}
    (counterexample :
      ModelFamilyCounterexample worldModel observe claim allowed) :
    ¬ ModelFamilyVerifies observe claim allowed := by
  intro verified
  exact counterexample.rightNotClaim
    ((verified counterexample.left counterexample.right
      counterexample.leftAllowed counterexample.rightAllowed
      counterexample.sameEvidence).mp counterexample.leftClaim)

end ModelFamilyCounterexample

/-- A proof-carrying demonstration that choosing one convenient semantics can
    underestimate the evidence required by the complete version space. -/
structure PointUnderestimationWitness
    {Model : Type u}
    {World : Type v}
    {Evidence : Type w}
    (worldModel : World → Model)
    (observe : World → Evidence)
    (claim : World → Prop)
    (allowed : World → Prop) where
  chosen : Model
  pointVerified :
    PointModelVerifies worldModel chosen observe claim allowed
  familyCounterexample :
    ModelFamilyCounterexample worldModel observe claim allowed

namespace PointUnderestimationWitness

theorem point_refinement_can_underestimate_evidence
    {Model : Type u}
    {World : Type v}
    {Evidence : Type w}
    {worldModel : World → Model}
    {observe : World → Evidence}
    {claim : World → Prop}
    {allowed : World → Prop}
    (witness :
      PointUnderestimationWitness worldModel observe claim allowed) :
    PointModelVerifies worldModel witness.chosen observe claim allowed ∧
      ¬ ModelFamilyVerifies observe claim allowed :=
  ⟨witness.pointVerified,
    witness.familyCounterexample.notFamilyVerifiable⟩

end PointUnderestimationWitness

/-- Channel selection that must work across every admissible model/history
    world, rather than only inside one chosen semantics. -/
def ModelFamilyChannelSelectionVerifies
    {World : Type u}
    {Channel : Type v}
    {Observation : Type w}
    (channel : Channel → World → Observation)
    (selected : Channel → Prop)
    (claim : World → Prop)
    (allowed : World → Prop) : Prop :=
  ∀ left right,
    allowed left →
      allowed right →
        ChannelsAgree channel selected left right →
          (claim left ↔ claim right)

/-- Adding consistent models/worlds cannot create a false positive when a
    verifier was already proved for the larger admissible family. -/
theorem family_verification_monotone_under_restriction
    {World : Type u}
    {Channel : Type v}
    {Observation : Type w}
    (channel : Channel → World → Observation)
    (selected : Channel → Prop)
    (claim : World → Prop)
    (larger smaller : World → Prop)
    (included : ∀ world, smaller world → larger world)
    (verifiedLarger :
      ModelFamilyChannelSelectionVerifies
        channel selected claim larger) :
    ModelFamilyChannelSelectionVerifies
      channel selected claim smaller := by
  intro left right leftAllowed rightAllowed sameEvidence
  exact verifiedLarger left right
    (included left leftAllowed)
    (included right rightAllowed)
    sameEvidence

end LeanFinance.Epistemic
