import LeanFinance.Backtest.Dataset
import LeanFinance.Backtest.FeatureLineage
import LeanFinance.Backtest.Decision

namespace LeanFinance.Backtest

/-- A derived feature gains an output content hash while preserving the legacy
    lineage record used by existing callers. -/
structure DerivedFeature where
  outputHash : ContentHash
  lineage : FeatureLineage
  deriving Repr

/-- All artifacts that may justify a decision-time feature. -/
structure LineageCatalog where
  datasets : List Dataset
  features : List DerivedFeature
  deriving Repr

/-- Recursive proof that an artifact was constructible by `availableBy`.

A dataset is a base case. A feature is available only when it was generated by
the requested time and every declared input was itself available by the
feature's own generation time. The latter condition prevents a feature from
being justified by an input that appeared later but still before the final
decision. Because this is inductive, a dependency cycle cannot justify itself
without a base artifact. -/
inductive ArtifactAvailableAt
    (catalog : LineageCatalog) : Timestamp → ContentHash → Prop where
  | dataset
      {availableBy : Timestamp}
      (dataset : Dataset)
      (member : dataset ∈ catalog.datasets)
      (available : DatasetAvailableAt dataset availableBy)
      (hashBound : DatasetHashBound dataset) :
      ArtifactAvailableAt catalog availableBy dataset.contentHash
  | feature
      {availableBy : Timestamp}
      (feature : DerivedFeature)
      (member : feature ∈ catalog.features)
      (outputBound : NonEmptyString feature.outputHash)
      (generated : FeatureAvailableAt feature.lineage availableBy)
      (lineageBound : FeatureBoundToInputs feature.lineage)
      (inputsAvailable :
        ∀ inputHash,
          inputHash ∈ feature.lineage.inputHashes →
          ArtifactAvailableAt catalog feature.lineage.generatedAt inputHash) :
      ArtifactAvailableAt catalog availableBy feature.outputHash

/-- Availability is monotone in time. The recursive feature inputs stay tied to
    the feature's generation time while the outer observation horizon widens. -/
theorem ArtifactAvailableAt.mono
    {catalog : LineageCatalog}
    {earlier later : Timestamp}
    {contentHash : ContentHash}
    (available : ArtifactAvailableAt catalog earlier contentHash)
    (timeOrder : earlier ≤ later) :
    ArtifactAvailableAt catalog later contentHash := by
  cases available with
  | dataset dataset member datasetAvailable hashBound =>
      exact ArtifactAvailableAt.dataset dataset member
        (Nat.le_trans datasetAvailable timeOrder) hashBound
  | feature feature member outputBound generated lineageBound inputsAvailable =>
      exact ArtifactAvailableAt.feature feature member outputBound
        (Nat.le_trans generated timeOrder) lineageBound inputsAvailable

/-- Every feature explicitly used by a decision must be represented by a
    recursively closed, point-in-time derivation in the catalog. -/
def DecisionLineageClosed
    (catalog : LineageCatalog)
    (decision : Decision) : Prop :=
  ∀ lineage,
    lineage ∈ decision.features →
    ∃ feature,
      feature ∈ catalog.features ∧
      feature.lineage = lineage ∧
      ArtifactAvailableAt catalog decision.decisionTime feature.outputHash

theorem DecisionLineageClosed.feature_has_recursive_proof
    (catalog : LineageCatalog)
    (decision : Decision)
    (closed : DecisionLineageClosed catalog decision)
    (lineage : FeatureLineage)
    (used : lineage ∈ decision.features) :
    ∃ feature : DerivedFeature,
      feature.lineage = lineage ∧
      ArtifactAvailableAt catalog decision.decisionTime feature.outputHash := by
  rcases closed lineage used with ⟨feature, _member, sameLineage, available⟩
  exact ⟨feature, sameLineage, available⟩

/-- Direct dataset leaves in a recursive derivation satisfy the same point-in-
    time condition used by `NoFutureInformation`. -/
theorem dataset_leaf_available_before_decision
    (catalog : LineageCatalog)
    (decisionTime : Timestamp)
    (dataset : Dataset)
    (member : dataset ∈ catalog.datasets)
    (available : DatasetAvailableAt dataset decisionTime)
    (hashBound : DatasetHashBound dataset) :
    ArtifactAvailableAt catalog decisionTime dataset.contentHash :=
  ArtifactAvailableAt.dataset dataset member available hashBound

end LeanFinance.Backtest
