import LeanFinance.Backtest.Dataset
import LeanFinance.Backtest.FeatureLineage
import LeanFinance.Backtest.Decision

namespace LeanFinance.Backtest

/-- A derived feature gains an output content hash while preserving the legacy
    lineage record used by existing callers. -/
structure DerivedFeature where
  outputHash : ContentHash
  lineage : FeatureLineage
  deriving Repr

/-- All artifacts that may justify a decision-time feature. -/
structure LineageCatalog where
  datasets : List Dataset
  features : List DerivedFeature
  deriving Repr

/-- Recursive proof that an artifact was constructible at `decisionTime`.

A dataset is a base case. A feature is available only when it was generated by
that time and every declared input hash itself has a finite availability proof.
Because this is inductive, a dependency cycle cannot justify itself without a
base artifact. -/
inductive ArtifactAvailableAt
    (catalog : LineageCatalog)
    (decisionTime : Timestamp) : ContentHash → Prop where
  | dataset
      (dataset : Dataset)
      (member : dataset ∈ catalog.datasets)
      (available : DatasetAvailableAt dataset decisionTime)
      (hashBound : DatasetHashBound dataset) :
      ArtifactAvailableAt catalog decisionTime dataset.contentHash
  | feature
      (feature : DerivedFeature)
      (member : feature ∈ catalog.features)
      (outputBound : NonEmptyString feature.outputHash)
      (generated : FeatureAvailableAt feature.lineage decisionTime)
      (lineageBound : FeatureBoundToInputs feature.lineage)
      (inputsAvailable :
        ∀ inputHash,
          inputHash ∈ feature.lineage.inputHashes →
          ArtifactAvailableAt catalog decisionTime inputHash) :
      ArtifactAvailableAt catalog decisionTime feature.outputHash

/-- Every feature explicitly used by a decision must be represented by a
    recursively closed, point-in-time derivation in the catalog. -/
def DecisionLineageClosed
    (catalog : LineageCatalog)
    (decision : Decision) : Prop :=
  ∀ lineage,
    lineage ∈ decision.features →
    ∃ feature,
      feature ∈ catalog.features ∧
      feature.lineage = lineage ∧
      ArtifactAvailableAt catalog decision.decisionTime feature.outputHash

theorem DecisionLineageClosed.feature_has_recursive_proof
    (catalog : LineageCatalog)
    (decision : Decision)
    (closed : DecisionLineageClosed catalog decision)
    (lineage : FeatureLineage)
    (used : lineage ∈ decision.features) :
    ∃ feature,
      feature.lineage = lineage ∧
      ArtifactAvailableAt catalog decision.decisionTime feature.outputHash := by
  rcases closed lineage used with ⟨feature, _member, sameLineage, available⟩
  exact ⟨feature, sameLineage, available⟩

/-- Direct dataset leaves in a recursive derivation satisfy the same point-in-
    time condition used by `NoFutureInformation`. -/
theorem dataset_leaf_available_before_decision
    (catalog : LineageCatalog)
    (decisionTime : Timestamp)
    (dataset : Dataset)
    (member : dataset ∈ catalog.datasets)
    (available : DatasetAvailableAt dataset decisionTime)
    (hashBound : DatasetHashBound dataset) :
    ArtifactAvailableAt catalog decisionTime dataset.contentHash :=
  ArtifactAvailableAt.dataset dataset member available hashBound

end LeanFinance.Backtest
