from __future__ import annotations

import re
from typing import Any

from .canonical import canonical_dumps
from .model import EvidenceModel

_LEAN_KEYWORDS = {
    "abbrev", "axiom", "by", "class", "def", "deriving", "do", "else",
    "end", "example", "export", "extends", "false", "forall", "fun", "if",
    "import", "in", "inductive", "infix", "instance", "let", "match",
    "namespace", "open", "opaque", "private", "protected", "structure",
    "syntax", "theorem", "true", "universe", "variable", "where", "with",
}


def lean_identifier(value: str, *, prefix: str) -> str:
    identifier = re.sub(r"[^A-Za-z0-9_]", "_", value)
    identifier = re.sub(r"_+", "_", identifier).strip("_")
    if not identifier:
        identifier = prefix
    identifier = identifier[0].lower() + identifier[1:]
    if identifier[0].isdigit():
        identifier = f"{prefix}_{identifier}"
    if identifier in _LEAN_KEYWORDS:
        identifier = f"{prefix}_{identifier}"
    return identifier


def _unique_identifiers(values: list[str], prefix: str) -> dict[str, str]:
    used: set[str] = set()
    result: dict[str, str] = {}
    for value in values:
        base = lean_identifier(value, prefix=prefix)
        candidate = base
        counter = 2
        while candidate in used:
            candidate = f"{base}_{counter}"
            counter += 1
        used.add(candidate)
        result[value] = candidate
    return result


def _lean_list(items: list[str]) -> str:
    return "[" + ", ".join(items) + "]"


def _candidate_name(mask: int) -> str:
    return f"mask{mask}"


def _render_inductive(name: str, constructors: list[str]) -> list[str]:
    lines = [f"inductive {name} where"]
    lines.extend(f"  | {constructor}" for constructor in constructors)
    lines.append("  deriving Repr, DecidableEq")
    lines.append("")
    return lines


def _counterexample_definition(
    *, name: str, candidate_name: str, left: str, right: str
) -> list[str]:
    return [
        f"def {name} :",
        f"    BoundedCounterexample model (decode .{candidate_name}) :=",
        "  {",
        f"    left := .{left}",
        f"    right := .{right}",
        "    leftMember := by simp [model, histories]",
        "    rightMember := by simp [model, histories]",
        "    claimDifferent := by simp [model, claim]",
        "    selectedAgree := by",
        "      intro evidenceChannel member",
        "      cases evidenceChannel <;>",
        "        simp [decode, model, observe] at member ⊢",
        "  }",
        "",
    ]


def render_lean(model: EvidenceModel, certificate: dict[str, Any]) -> str:
    history_ids = [history.id for history in model.histories]
    channel_ids = [channel.id for channel in model.channels]
    history_ident = _unique_identifiers(history_ids, "history")
    channel_ident = _unique_identifiers(channel_ids, "channel")

    observation_values: list[str] = []
    for channel in model.channels:
        for history in model.histories:
            encoded = canonical_dumps(channel.observations[history.id])
            if encoded not in observation_values:
                observation_values.append(encoded)
    observation_ident = {
        encoded: f"obs{index}" for index, encoded in enumerate(observation_values)
    }

    candidate_count = 1 << len(model.channels)
    candidate_names = [_candidate_name(mask) for mask in range(candidate_count)]
    lines: list[str] = [
        "import LeanFinance.Epistemic.FiniteSynthesis",
        "",
        f"namespace {model.namespace}",
        "",
        "open LeanFinance.Epistemic",
        "",
        "/-- Generated by `python -m tools.evidence_synth synth`. Do not edit by hand. -/",
        "",
    ]
    lines += _render_inductive("History", [history_ident[v] for v in history_ids])
    lines += _render_inductive("Channel", [channel_ident[v] for v in channel_ids])
    lines += _render_inductive(
        "Observation", [observation_ident[v] for v in observation_values]
    )
    lines += [
        "def histories : List History :=",
        "  " + _lean_list([f".{history_ident[v]}" for v in history_ids]),
        "",
        "def channels : List Channel :=",
        "  " + _lean_list([f".{channel_ident[v]}" for v in channel_ids]),
        "",
        "def observe : Channel → History → Observation",
    ]
    for channel in model.channels:
        for history in model.histories:
            observation = observation_ident[
                canonical_dumps(channel.observations[history.id])
            ]
            lines.append(
                f"  | .{channel_ident[channel.id]}, .{history_ident[history.id]} => .{observation}"
            )
    lines.append("")
    lines.append("def claim : History → Bool")
    for history in model.histories:
        value = "true" if history.claim else "false"
        lines.append(f"  | .{history_ident[history.id]} => {value}")
    lines.append("")
    lines.append("def cost : Channel → Nat")
    for channel in model.channels:
        lines.append(
            f"  | .{channel_ident[channel.id]} => {model.weighted_channel_cost(channel.id)}"
        )
    lines.append("")
    lines += [
        "def model : BoundedEvidenceModel History Channel Observation :=",
        "  {",
        "    histories := histories",
        "    channels := channels",
        "    observe := observe",
        "    claim := claim",
        "    cost := cost",
        "  }",
        "",
    ]
    lines += _render_inductive("Candidate", candidate_names)
    lines.append("def decode : Candidate → List Channel")
    for mask in range(candidate_count):
        selected = [
            f".{channel_ident[channel.id]}"
            for index, channel in enumerate(model.channels)
            if mask & (1 << index)
        ]
        lines.append(f"  | .{_candidate_name(mask)} => {_lean_list(selected)}")
    lines.append("")

    edge_by_id = {edge["id"]: edge for edge in certificate["disagreement_edges"]}
    if certificate["status"] == "impossible":
        witness = certificate["impossibility_witness"]
        all_mask = certificate["all_channels_mask"]
        lines += _counterexample_definition(
            name="allChannelsCounterexample",
            candidate_name=_candidate_name(all_mask),
            left=history_ident[witness["left"]],
            right=history_ident[witness["right"]],
        )
        lines += [
            "theorem all_channels_cannot_verify :",
            f"    ¬ BoundedSelectionVerifies model (decode .{_candidate_name(all_mask)}) :=",
            "  allChannelsCounterexample.notBoundedVerifies",
            "",
            f"end {model.namespace}",
            "",
        ]
        return "\n".join(lines)

    selected_mask = certificate["selected"]["mask"]
    lines += [
        "def selected : Candidate :=",
        f"  .{_candidate_name(selected_mask)}",
        "",
        "theorem selectedBoundedlyVerifies :",
        "    BoundedSelectionVerifies model (decode selected) := by",
        "  apply boundedVerifiesBool_sound",
        "  decide",
        "",
    ]
    lower_cost_failures = certificate["lower_cost_failures"]
    failure_by_mask = {failure["mask"]: failure for failure in lower_cost_failures}
    for failure in lower_cost_failures:
        edge = edge_by_id[failure["uncovered_edge"]]
        mask = failure["mask"]
        lines += _counterexample_definition(
            name=f"counterexample_{_candidate_name(mask)}",
            candidate_name=_candidate_name(mask),
            left=history_ident[edge["left"]],
            right=history_ident[edge["right"]],
        )
    lines += [
        "def cheaperCandidateCounterexample",
        "    (candidate : Candidate)",
        "    (cheaper :",
        "      selectionCost model (decode candidate) <",
        "        selectionCost model (decode selected)) :",
        "    BoundedCounterexample model (decode candidate) := by",
        "  cases candidate with",
    ]
    for mask in range(candidate_count):
        name = _candidate_name(mask)
        if mask in failure_by_mask:
            lines.append(f"  | {name} => exact counterexample_{name}")
        else:
            lines += [
                f"  | {name} =>",
                "      simp [selectionCost, model, decode, selected, cost] at cheaper",
            ]
    lines.append("")
    lines += [
        "def synthesisCertificate :",
        "    BoundedSynthesisCertificate model Candidate decode selected :=",
        "  {",
        "    historyComplete := by",
        "      intro history",
        "      cases history <;> simp [model, histories]",
        "    selectedVerifies := selectedBoundedlyVerifies",
        "    lowerCostCounterexample := cheaperCandidateCounterexample",
        "  }",
        "",
        "theorem synthesized_selection_semantically_verifies :",
        "    ChannelSelectionVerifies",
        "      model.observe",
        "      (fun evidenceChannel =>",
        "        evidenceChannel ∈ decode selected)",
        "      model.ClaimHolds :=",
        "  synthesisCertificate.selectedSemanticallyVerifies",
        "",
        "theorem synthesized_selection_is_cost_minimal",
        "    (candidate : Candidate)",
        "    (candidateVerifies :",
        "      BoundedSelectionVerifies model (decode candidate)) :",
        "    selectionCost model (decode selected) ≤",
        "      selectionCost model (decode candidate) :=",
        "  synthesisCertificate.selectedCostLeOfCandidateVerifies",
        "    candidate candidateVerifies",
        "",
        f"end {model.namespace}",
        "",
    ]
    return "\n".join(lines)
